name: Build Windows
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: environment-win-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build - ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: windows-latest
            name: "Windows x64 MSVC"
            artifact: "Windows-MSVC.tar.xz"
            build_type: "RelWithDebInfo"
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
            cc: "cl"
            cxx: "cl"
            archiver: "7z a"
            generators: "Visual Studio 17 2022"
            build_dir: 'build'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          
      - name: Setup Pragma Module
        id: pragma-cmake-defs
        uses: Silverlan/common_actions/setup_pragma_module@main
        with:
          cc_version: ${{ matrix.cc }}
          cxx_version: ${{ matrix.cxx }}
          
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          
      - name: Build
        shell: bash
        run: |
          cmake -G "Unix Makefiles" \
            ${{ steps.pragma-cmake-defs.outputs.cmake_defs }} \
            -DDEPENDENCY_PYTHON_INCLUDE="$pythonLocation/include/" \
            -DDEPENDENCY_PYTHON_LIBRARY="$pythonLocation/libs/python310.lib"
          cmake --build ./ --verbose --target pr_python

      - name: Create Release Files
        shell: bash
        run: |
          mkdir release
          mkdir release/modules
          rsync --mkpath ./pr_python.dll release/modules/python/
          rsync --mkpath $pythonLocation/python310.dll release/modules/python/
          
      - name: Release Binaries
        uses: Silverlan/common_actions/release_nightly_binaries@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: ${{ github.ref_name }}

      - name: Handle Error
        uses: Silverlan/common_actions/action_handle_error@main
        if: failure()
        
